services:
  finance-admin:
    build:
      target: dev
    ports:
      - '2345:2345'
    volumes:
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./shared:/app/shared
      - ./apierror:/app/apierror
      - ./finance-admin/.air.toml:/app/finance-admin/.air.toml
      - ./finance-admin/internal:/app/finance-admin/internal
      - ./finance-admin/main_test.go:/app/finance-admin/main_test.go
      - ./finance-admin/main.go:/app/finance-admin/main.go
      - ./finance-admin/web/static:/app/finance-admin/web/static
      - ./finance-admin/web/template:/app/finance-admin/web/template

  yarn:
    command: watch

  json-server:
    volumes:
      - ./json-server/config:/app/config
