// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface { 
	CustomersSchemeCodeMandatesCreatePost(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeVariableMandatesCreatePost(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountsPut(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountsDelete(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountEmailPut(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesGet(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesPut(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesPost(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameVariableMandatesPost(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesScheduleGet(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete(http.ResponseWriter, *http.Request)
	CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet(http.ResponseWriter, *http.Request)
	BankAccountsGet(http.ResponseWriter, *http.Request)
}


// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface { 
	CustomersSchemeCodeMandatesCreatePost(context.Context, string, CustomersSchemeCodeMandatesCreatePostRequest) (ImplResponse, error)
	CustomersSchemeCodeVariableMandatesCreatePost(context.Context, string, CustomersSchemeCodeVariableMandatesCreatePostRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountsPut(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameBankAccountsPutRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountsDelete(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountEmailPut(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesGet(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesPut(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameMandatesPutRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesPost(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameMandatesPostRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameVariableMandatesPost(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameVariableMandatesPostRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost(context.Context, string, string, string, CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesScheduleGet(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete(context.Context, string, string, string, string, int32) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet(context.Context, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete(context.Context, string, string, string, string) (ImplResponse, error)
	CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet(context.Context, string, string, string, int32) (ImplResponse, error)
	BankAccountsGet(context.Context, string, string) (ImplResponse, error)
}
