// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// CustomersSchemeCodeMandatesCreatePost - Create Mandate
func (s *DefaultAPIService) CustomersSchemeCodeMandatesCreatePost(ctx context.Context, schemeCode string, customersSchemeCodeMandatesCreatePostRequest CustomersSchemeCodeMandatesCreatePostRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeMandatesCreatePost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeMandatesCreatePost method not implemented")
}

// CustomersSchemeCodeVariableMandatesCreatePost - Create Variable Mandate
func (s *DefaultAPIService) CustomersSchemeCodeVariableMandatesCreatePost(ctx context.Context, schemeCode string, customersSchemeCodeVariableMandatesCreatePostRequest CustomersSchemeCodeVariableMandatesCreatePostRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeVariableMandatesCreatePost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeVariableMandatesCreatePost method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountsPut - Edit Bank Account Holder Details
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountsPut(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameBankAccountsPutRequest CustomersSchemeCodeClientRefSurnameBankAccountsPutRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountsPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountsPut method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountsDelete - Delete Bank Account Holder Details
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountsDelete(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountsDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountsDelete method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountEmailPut - Edit Email Address
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountEmailPut(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameBankAccountEmailPutRequest CustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountEmailPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountEmailPut method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete - Delete Email Address
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut - Edit Mobile Number
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPut method not implemented")
}

// CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete - Delete Mobile Number
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberDelete method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesGet - Retrieve Mandate Information
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesGet(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesGet method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesPut - Add Immediate Payment Schedule
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesPut(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameMandatesPutRequest CustomersSchemeCodeClientRefSurnameMandatesPutRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesPut method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesPost - Add Payment Schedule to an Existing Mandate
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesPost(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameMandatesPostRequest CustomersSchemeCodeClientRefSurnameMandatesPostRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesCreatePost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesPost method not implemented")
}

// CustomersSchemeCodeClientRefSurnameVariableMandatesPost - Add Payment Schedule to an Existing Variable Mandate
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameVariableMandatesPost(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameVariableMandatesPostRequest CustomersSchemeCodeClientRefSurnameVariableMandatesPostRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameVariableMandatesPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameVariableMandatesPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameVariableMandatesPost200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameVariableMandatesPost method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost - Add Annual Renewal Schedule
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost(ctx context.Context, schemeCode string, clientRef string, surname string, customersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPost method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesScheduleGet - Retrieve Schedule Components
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesScheduleGet(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesScheduleGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesScheduleGet method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet - Retrieve Payment Schedule
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete - Remove Schedule Components
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete(ctx context.Context, schemeCode string, clientRef string, surname string, firstPaymentDate string, amount int32) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet - Show Previous Collection History
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet(ctx context.Context, schemeCode string, clientRef string, surname string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet method not implemented")
}

// CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete - Close Mandate
func (s *DefaultAPIService) CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete(ctx context.Context, schemeCode string, clientRef string, surname string, closureDate string) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeClientRefSurnameMandatesPut200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeClientRefSurnameMandatesClosureDateDelete method not implemented")
}

// CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet - Retrieve Failed Payments
func (s *DefaultAPIService) CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet(ctx context.Context, schemeCode string, fromDate string, toDate string, pageNumber int32) (ImplResponse, error) {
	// TODO - update CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(401, {}) or use other options such as http.Ok ...
	// return Response(401, nil),nil

	// TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	// return Response(404, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet method not implemented")
}

// BankAccountsGet - Modulus Check
func (s *DefaultAPIService) BankAccountsGet(ctx context.Context, sortcode string, accountnumber string) (ImplResponse, error) {
	// TODO - update BankAccountsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, BankAccountsGet200Response{}) or use other options such as http.Ok ...
	// return Response(200, BankAccountsGet200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	// return Response(400, nil),nil

	// TODO: Uncomment the next line to return response Response(422, {}) or use other options such as http.Ok ...
	// return Response(422, nil),nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("BankAccountsGet method not implemented")
}
