// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameVariableMandatesPostRequest struct {

	Schedules []CustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInner `json:"Schedules,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPostRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPostRequestRequired(obj CustomersSchemeCodeClientRefSurnameVariableMandatesPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPostRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPostRequestConstraints(obj CustomersSchemeCodeClientRefSurnameVariableMandatesPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
