// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInner struct {

	Amount int32 `json:"Amount,omitempty"`

	Frequency string `json:"Frequency,omitempty"`

	PaymentDate string `json:"PaymentDate,omitempty"`

	Type string `json:"Type,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInner) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInner) error {
	return nil
}
