// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200Response struct {

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`

	SchemeCode string `json:"SchemeCode,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200Response) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleFirstPaymentDateAmountDelete200Response) error {
	return nil
}
