// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPut200Response struct {

	Success bool `json:"success,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPut200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPut200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPut200Response) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPut200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPut200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPut200Response) error {
	return nil
}
