// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200Response struct {

	FailedPayments []CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInner `json:"failedPayments,omitempty"`
}

// AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseRequired(obj CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200Response) error {
	for _, el := range obj.FailedPayments {
		if err := AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseConstraints(obj CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200Response) error {
	for _, el := range obj.FailedPayments {
		if err := AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
