// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInner struct {

	ScheduleDate string `json:"ScheduleDate,omitempty"`

	Amount int32 `json:"Amount,omitempty"`

	Frequency string `json:"Frequency,omitempty"`

	TotalPayments int32 `json:"TotalPayments,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInner) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInner) error {
	return nil
}
