// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPostRequest struct {

	Schedules []CustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInner `json:"Schedules,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
