// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameBankAccountsPutRequest struct {

	Address CustomersSchemeCodeClientRefSurnameBankAccountsPutRequestAddress `json:"Address,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestRequired(obj CustomersSchemeCodeClientRefSurnameBankAccountsPutRequest) error {
	if err := AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestConstraints(obj CustomersSchemeCodeClientRefSurnameBankAccountsPutRequest) error {
	if err := AssertCustomersSchemeCodeClientRefSurnameBankAccountsPutRequestAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
