// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeVariableMandatesCreatePostRequest struct {

	Customer CustomersSchemeCodeMandatesCreatePostRequestCustomer `json:"Customer,omitempty"`

	Schedules []CustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInner `json:"Schedules,omitempty"`

	BankAccount CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccount `json:"BankAccount,omitempty"`
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestRequired(obj CustomersSchemeCodeVariableMandatesCreatePostRequest) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerRequired(obj.Customer); err != nil {
		return err
	}
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountRequired(obj.BankAccount); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestConstraints(obj CustomersSchemeCodeVariableMandatesCreatePostRequest) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerConstraints(obj.Customer); err != nil {
		return err
	}
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountConstraints(obj.BankAccount); err != nil {
		return err
	}
	return nil
}
