// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequestSchedulesInner struct {

	ScheduleDate string `json:"ScheduleDate,omitempty"`

	Amount int32 `json:"Amount,omitempty"`

	Frequency string `json:"Frequency,omitempty"`

	TotalPayments int32 `json:"TotalPayments,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerRequired(obj CustomersSchemeCodeMandatesCreatePostRequestSchedulesInner) error {
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerConstraints(obj CustomersSchemeCodeMandatesCreatePostRequestSchedulesInner) error {
	return nil
}
