// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInner struct {

	Amount int32 `json:"Amount,omitempty"`

	PaymentDate string `json:"PaymentDate,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInner) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInner) error {
	return nil
}
