// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesGet200Response struct {

	Address CustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddress `json:"Address,omitempty"`

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`

	SchemeCode string `json:"SchemeCode,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesGet200Response) error {
	if err := AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesGet200Response) error {
	if err := AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
