// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInner struct {

	Amount int32 `json:"Amount,omitempty"`

	CollectionDay string `json:"CollectionDay,omitempty"`

	FirstPaymentDate string `json:"FirstPaymentDate,omitempty"`

	Frequency string `json:"Frequency,omitempty"`

	NextPaymentDate string `json:"NextPaymentDate,omitempty"`

	PaymentsRequested int32 `json:"PaymentsRequested,omitempty"`

	PreviousPaymentDate string `json:"PreviousPaymentDate,omitempty"`

	RemainingPayments string `json:"RemainingPayments,omitempty"`

	TotalPayments string `json:"TotalPayments,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerRequired(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInner) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInner) error {
	return nil
}
