// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest struct {

	MobileNumber string `json:"MobileNumber,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequestRequired(obj CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequestConstraints(obj CustomersSchemeCodeClientRefSurnameBankAccountMobileNumberPutRequest) error {
	return nil
}
