// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequestCustomer struct {

	MobileNumber string `json:"MobileNumber,omitempty"`

	Email string `json:"Email,omitempty"`

	TitleInitials string `json:"TitleInitials,omitempty"`

	Address CustomersSchemeCodeMandatesCreatePostRequestCustomerAddress `json:"Address,omitempty"`

	SchemeCode string `json:"SchemeCode,omitempty"`

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerRequired(obj CustomersSchemeCodeMandatesCreatePostRequestCustomer) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerConstraints(obj CustomersSchemeCodeMandatesCreatePostRequestCustomer) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
