// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200Response struct {

	SchemeCode string `json:"SchemeCode,omitempty"`

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200Response) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameBankAccountEmailDelete200Response) error {
	return nil
}
