// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddress struct {

	TitleInitials string `json:"TitleInitials,omitempty"`

	LastName string `json:"LastName,omitempty"`

	County string `json:"County,omitempty"`

	Line1 string `json:"Line1,omitempty"`

	Line2 string `json:"Line2,omitempty"`

	Town string `json:"Town,omitempty"`

	PostCode string `json:"PostCode,omitempty"`
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressRequired(obj CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddress) error {
	return nil
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressConstraints(obj CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddress) error {
	return nil
}
