// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type BankAccountsGet200ResponseAddress struct {

	Line1 string `json:"line1,omitempty"`

	Line2 string `json:"line2,omitempty"`

	Town string `json:"town,omitempty"`

	Postcode string `json:"postcode,omitempty"`
}

// AssertBankAccountsGet200ResponseAddressRequired checks if the required fields are not zero-ed
func AssertBankAccountsGet200ResponseAddressRequired(obj BankAccountsGet200ResponseAddress) error {
	return nil
}

// AssertBankAccountsGet200ResponseAddressConstraints checks if the values respects the defined constraints
func AssertBankAccountsGet200ResponseAddressConstraints(obj BankAccountsGet200ResponseAddress) error {
	return nil
}
