// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddress struct {

	County string `json:"County,omitempty"`

	LastName string `json:"LastName,omitempty"`

	Line1 string `json:"Line1,omitempty"`

	Line2 string `json:"Line2,omitempty"`

	PostCode string `json:"PostCode,omitempty"`

	TitleInitials string `json:"TitleInitials,omitempty"`

	Town string `json:"Town,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressRequired(obj CustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddress) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddressConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesGet200ResponseAddress) error {
	return nil
}
