// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi


import (
	"time"
)



type CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInner struct {

	Amount int32 `json:"amount,omitempty"`

	ClientReference string `json:"clientReference,omitempty"`

	CollectionDate time.Time `json:"collectionDate,omitempty"`

	IsRepresented bool `json:"isRepresented,omitempty"`

	LastName string `json:"lastName,omitempty"`

	Line1 string `json:"line1,omitempty"`

	ProcessedDate time.Time `json:"processedDate,omitempty"`

	ReasonCode string `json:"reasonCode,omitempty"`

	SchemeCode string `json:"schemeCode,omitempty"`
}

// AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerRequired(obj CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInner) error {
	return nil
}

// AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInnerConstraints(obj CustomersSchemeCodeMandatesFailedPaymentsFromDateToDatePageNumberGet200ResponseFailedPaymentsInner) error {
	return nil
}
