// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type BankAccountsGet200Response struct {

	Valid bool `json:"valid,omitempty"`

	BankName string `json:"bankName,omitempty"`

	Branch string `json:"branch,omitempty"`

	Address BankAccountsGet200ResponseAddress `json:"address,omitempty"`

	DirectDebitCapable bool `json:"directDebitCapable,omitempty"`

	DirectCreditCapable bool `json:"directCreditCapable,omitempty"`
}

// AssertBankAccountsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertBankAccountsGet200ResponseRequired(obj BankAccountsGet200Response) error {
	if err := AssertBankAccountsGet200ResponseAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertBankAccountsGet200ResponseConstraints checks if the values respects the defined constraints
func AssertBankAccountsGet200ResponseConstraints(obj BankAccountsGet200Response) error {
	if err := AssertBankAccountsGet200ResponseAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
