// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequest struct {

	Customer CustomersSchemeCodeMandatesCreatePostRequestCustomer `json:"Customer,omitempty"`

	Schedules []CustomersSchemeCodeMandatesCreatePostRequestSchedulesInner `json:"Schedules,omitempty"`

	BankAccount CustomersSchemeCodeMandatesCreatePostRequestBankAccount `json:"BankAccount,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestRequired(obj CustomersSchemeCodeMandatesCreatePostRequest) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerRequired(obj.Customer); err != nil {
		return err
	}
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountRequired(obj.BankAccount); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestConstraints(obj CustomersSchemeCodeMandatesCreatePostRequest) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerConstraints(obj.Customer); err != nil {
		return err
	}
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountConstraints(obj.BankAccount); err != nil {
		return err
	}
	return nil
}
