// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200Response struct {

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`

	Payments []CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInner `json:"Payments,omitempty"`

	SchemeCode string `json:"SchemeCode,omitempty"`

	TotalRecords int32 `json:"TotalRecords,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200Response) error {
	for _, el := range obj.Payments {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200Response) error {
	for _, el := range obj.Payments {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentHistoryGet200ResponsePaymentsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
