// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePost200Response struct {

	SchemeCode string `json:"SchemeCode,omitempty"`

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePost200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePost200ResponseRequired(obj CustomersSchemeCodeMandatesCreatePost200Response) error {
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePost200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePost200ResponseConstraints(obj CustomersSchemeCodeMandatesCreatePost200Response) error {
	return nil
}
