// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPutRequest struct {

	Schedules []CustomersSchemeCodeMandatesCreatePostRequestSchedulesInner `json:"Schedules,omitempty"`

	SuppressNotification int32 `json:"SuppressNotification,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPutRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPutRequestRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPutRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPutRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPutRequestConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPutRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeMandatesCreatePostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
