// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccount struct {

	BankDetails CustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetails `json:"BankDetails,omitempty"`

	Address CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddress `json:"Address,omitempty"`
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountRequired(obj CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccount) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsRequired(obj.BankDetails); err != nil {
		return err
	}
	if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountConstraints(obj CustomersSchemeCodeVariableMandatesCreatePostRequestBankAccount) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsConstraints(obj.BankDetails); err != nil {
		return err
	}
	if err := AssertCustomersSchemeCodeVariableMandatesCreatePostRequestBankAccountAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
