// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200Response struct {

	ClientReference string `json:"ClientReference,omitempty"`

	LastName string `json:"LastName,omitempty"`

	Payments []CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInner `json:"Payments,omitempty"`

	SchemeCode string `json:"SchemeCode,omitempty"`

	TotalRecords int32 `json:"TotalRecords,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200Response) error {
	for _, el := range obj.Payments {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200Response) error {
	for _, el := range obj.Payments {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesPaymentsGet200ResponsePaymentsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
