// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequestBankAccount struct {

	BankDetails CustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetails `json:"BankDetails,omitempty"`

	Address CustomersSchemeCodeMandatesCreatePostRequestBankAccountAddress `json:"Address,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountRequired(obj CustomersSchemeCodeMandatesCreatePostRequestBankAccount) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsRequired(obj.BankDetails); err != nil {
		return err
	}
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountAddressRequired(obj.Address); err != nil {
		return err
	}
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountConstraints(obj CustomersSchemeCodeMandatesCreatePostRequestBankAccount) error {
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsConstraints(obj.BankDetails); err != nil {
		return err
	}
	if err := AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountAddressConstraints(obj.Address); err != nil {
		return err
	}
	return nil
}
