// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetails struct {

	AccountName string `json:"AccountName,omitempty"`

	SortCode string `json:"SortCode,omitempty"`

	AccountNumber string `json:"AccountNumber,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsRequired(obj CustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetails) error {
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetailsConstraints(obj CustomersSchemeCodeMandatesCreatePostRequestBankAccountBankDetails) error {
	return nil
}
