// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameVariableMandatesPost200Response struct {

	MandateId string `json:"mandateId,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPost200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPost200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameVariableMandatesPost200Response) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPost200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameVariableMandatesPost200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameVariableMandatesPost200Response) error {
	return nil
}
