// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInner struct {

	ScheduleDate string `json:"ScheduleDate,omitempty"`

	Amount int32 `json:"Amount,omitempty"`
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerRequired(obj CustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInner) error {
	return nil
}

// AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInnerConstraints(obj CustomersSchemeCodeVariableMandatesCreatePostRequestSchedulesInner) error {
	return nil
}
