// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeMandatesCreatePostRequestCustomerAddress struct {

	Line1 string `json:"Line1,omitempty"`

	Line2 string `json:"Line2,omitempty"`

	Town string `json:"Town,omitempty"`

	County string `json:"County,omitempty"`

	PostCode string `json:"PostCode,omitempty"`
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressRequired(obj CustomersSchemeCodeMandatesCreatePostRequestCustomerAddress) error {
	return nil
}

// AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeMandatesCreatePostRequestCustomerAddressConstraints(obj CustomersSchemeCodeMandatesCreatePostRequestCustomerAddress) error {
	return nil
}
