// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest struct {

	Schedules []CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestSchedulesInner `json:"Schedules,omitempty"`

	SuppressNotification int32 `json:"SuppressNotification,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestRequired(obj CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequest) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesAnnualRenewalPostRequestSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
