// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200Response struct {

	Schedules []CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInner `json:"Schedules,omitempty"`

	TotalRecords int32 `json:"TotalRecords,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseRequired(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200Response) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseConstraints(obj CustomersSchemeCodeClientRefSurnameMandatesScheduleGet200Response) error {
	for _, el := range obj.Schedules {
		if err := AssertCustomersSchemeCodeClientRefSurnameMandatesScheduleGet200ResponseSchedulesInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
