// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * AllPay Direct Debit API
 *
 * API for managing Direct Debit mandates and schedules.
 *
 * API version: 1.0.0
 */

package openapi




type CustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequest struct {

	Email string `json:"Email,omitempty"`
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequestRequired checks if the required fields are not zero-ed
func AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequestRequired(obj CustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequest) error {
	return nil
}

// AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequestConstraints checks if the values respects the defined constraints
func AssertCustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequestConstraints(obj CustomersSchemeCodeClientRefSurnameBankAccountEmailPutRequest) error {
	return nil
}
